version: "3"

includes:
  docs: 
    taskfile: "docs/sphinx/Taskfile.yaml"
    dir: "./docs/sphinx"

tasks:
  default:
    cmds:
      - task --list-all
  
  install-hooks:
    desc: Install pre-commit hooks
    dir: "./misc"
    cmds:
      - uv run pre-commit install

  install:
    desc: Install all dependencies
    cmds:
      - uv sync --directory=./lib
      # - uv sync --directory=./projects/shortest_path
      # - uv sync --directory=./projects/tsp
